site_name: My Docs
theme:
  name: material

nav:     
  - Tutorials:
    - 'Deployment':
      - Intro: 'deployment/intro.md'
      - ONNX: 'deployment/onnx.md'
      - Torchscript: 'deployment/torchscript.md'
    - 'Experiment Tracking': 
      - Tensorboard: 'experiment-tracking/tensorboard.md'
      - Aim: 'experiment-tracking/aim.md'
      - MLFlow: 'experiment-tracking/mlflow.md'
    - 'Configurable Parameters': 
      - Intro: 'config/intro.md'

plugins:
  - search:
      lang: en