site_name: My Docs
theme:
  name: material

nav:     
  - Tutorials:
    - 'Deployment':
      - intro: 'deployment/intro.md'
      - onnx: 'deployment/onnx.md'
      - torchscript: 'deployment/torchscript.md'

plugins:
  - search:
      lang: en